[package]
name = "rust_actix_diesel"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
diesel = { version = "2.1.0", features = ["postgres", "r2d2"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
